stages:
  - test
  - build
  - deploy

# TEST
Linter:
  image: golangci/golangci-lint:v1.30
  stage: test
  tags: [docker]
  script:
    - golangci-lint run -v
    - go test -mod=vendor -v -race ./...
  except:
    - master

# BUILD
.Build template: &build_template
  image: docker:stable
  stage: build
  tags: [docker]
  script:
    # Login Docker-registry
    - docker login -u "gitlab-ci-token" -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    # Make BUILD_INFO
    - >
      BUILD_INFO="[$(date +'%Y-%m-%d %H:%M:%S %z')] $(docker -v)
        Git[$CI_PROJECT_URL] Reference[$CI_COMMIT_REF_NAME] $CI_COMMIT_SHA
        Pipeline[$CI_PIPELINE_ID] Env[$CI_ENVIRONMENT_NAME] Build[$CI_BUILD_ID] User[$GITLAB_USER_LOGIN]
        Runner[$CI_RUNNER_ID:$CI_RUNNER_DESCRIPTION]"
    - echo $BUILD_INFO

    # Build
    - |
      docker build -f ./Dockerfile \
        --build-arg BUILD_INFO="${BUILD_INFO}" \
        --build-arg CI_COMMIT_TAG="${CI_COMMIT_TAG}" \
        --build-arg UPX_LEVEL="${UPX_LEVEL}" \
        --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} \
        .

    # Push into Docker-registry
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    # Print the job's end time
    - date "+'%Y-%m-%d %H:%M:%S %z'"

Build Dev (auto):
  <<: *build_template
  environment:
    name: "dev"
  only:
    - /^[0-9.]{1,8}[.-](alpha|beta)[0-9.]{1,3}$/
  variables:
    UPX_LEVEL: "9"

Build Stage (auto):
  <<: *build_template
  environment:
    name: "stage"
  only:
    - /^[0-9.]{1,8}[.-](rc)[0-9.]{1,3}$/
    - /^[0-9.]{1,8}$/
  variables:
    UPX_LEVEL: "9"

# DEPLOY
.Deploy template: &deploy_template
  image: dtzar/helm-kubectl:3.7.2
  stage: deploy
  tags: [docker]
  script:
    - mkdir ~/.kube
    - echo ${K8S_CONFIG} | base64 -d > ~/.kube/config
    - egrep "current-context|name|server" ~/.kube/config
    - kubectl version
    # Apply Changes
    - kubectl set image deployment/${CI_PROJECT_NAME} --namespace ${NAMESPACE} ${CI_PROJECT_NAME}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  variables:
    K8S_CONFIG: "${KUBE_CONFIG}"

Deploy Alpha (auto):
  <<: *deploy_template
  tags: [docker, office]
  environment:
    name: "dev"
  only:
    - /^[0-9.]{1,8}[.-](alpha|beta)[0-9.]{1,3}$/
  variables:
    K8S_CONFIG: '${KUBE_CONFIG_ALPHA}'
    NAMESPACE: 'default'

Deploy Beta (auto):
  <<: *deploy_template
  tags: [docker, office]
  environment:
    name: "dev"
  only:
    - /^[0-9.]{1,8}[.-](beta|rc)[0-9.]{1,3}$/
  variables:
    K8S_CONFIG: '${KUBE_CONFIG_BETA}'
    NAMESPACE: 'default'

Deploy Cert (auto):
  <<: *deploy_template
  tags: [docker, office]
  environment:
    name: 'cert'
  only:
    - /^[0-9.]{1,8}[.-](beta|rc)[0-9.]{1,3}$/
  variables:
    K8S_CONFIG: '${KUBE_CONFIG_CERT}'
    NAMESPACE: 'au'

Deploy Stage (auto):
  <<: *deploy_template
  environment:
    name: "stage"
  only:
    - /^[0-9.]{1,8}[.-](rc)[0-9.]{1,3}$/
    - /^[0-9.]{1,8}$/
  variables:
    K8S_CONFIG: '${KUBE_CONFIG_STAGE}'
    NAMESPACE: 'default'
