replicaCount: 2

service:
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: k8s.n.rasla.ru
      paths:
        - path: /echo2/(.*)
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1  # /api/$2

resources:
   requests:
     cpu: 10m
     memory: 32Mi
