# global config
global:
  scrape_interval:     10s # Set the scrape interval to every 10 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 10 seconds. The default is every 1 minute.

# A scrape configuration
scrape_configs:
  # Scrape Prometheus itself (Dashboard #3662)
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'localhost:9090'

  # Scrape the Node Exporter (nix) - https://github.com/prometheus/node_exporter
  # Grafana Dashboards: 11074, 1860
  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'node_exporter:9100'
          #- '172.17.0.1:9100'  ## Docker Host-OS
          #- '192.168.110.24:9100'   # devops-rasla

  # Scrape the WMI Exporter - https://github.com/martinlindhe/wmi_exporter
  # Grafana Dashboards: 2129
  - job_name: 'node-windows'
    scrape_interval: 10s
    static_configs:
      - targets:
          # Windows host-metrics, by
          - '192.168.110.19:9182'   # stas-pc

  # Scrape the cAdvisor - https://github.com/google/cadvisor
  # Grafana Dashboards: 8321
  - job_name: docker
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'cadvisor:8080'

  # Scrape the RabbitMQ Exporter - https://github.com/kbudde/rabbitmq_exporter
  # Grafana Dashboards: 4279
#  - job_name: rabbitmq_exporter
#    scrape_interval: 20s
#    static_configs:
#      - targets:
#          - '192.168.110.15:9419'  # des-pc

  # Scrape the Redis Exporter - https://github.com/oliver006/redis_exporter
  # Grafana Dashboards: 763
#  - job_name: redis_exporter
#    scrape_interval: 10s
#    static_configs:
#      - targets:
#          #- 'localhost:9121'

  # Scrape the Postgres Exporter - https://github.com/wrouesnel/postgres_exporter
  # Grafana Dashboards: 6742
#  - job_name: postgres_exporter
#    scrape_interval: 10s
#    static_configs:
#      - targets:
#          #- 'localhost:9187'
