kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-admin
  namespace: test
subjects:
- kind: ServiceAccount
  name: test-user
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin