kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-admin
  namespace: test
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "services", "ingresses"]  # "secrets"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]  # You can also use ["*"]
